services:
  backend:
    build: ./mini-grader-be
    container_name: mini-grader-be
    env_file:
      - ./mini-grader-be/.env
    ports:
      - '8000:8000'
    environment: 
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mini-grader-network

  database:
    image: mysql
    container_name: mini-grader-db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: minigrader
    ports:
      - '3310:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    networks:
      - mini-grader-network

networks:
  mini-grader-network:
